FROM node:18-alpine as dev

WORKDIR /app

COPY package.json .
RUN npm i
RUN chown -R node:node /app/node_modules

##############################################################

FROM dev as builder

WORKDIR /app

COPY . .

RUN npm run build

##############################################################

FROM nginx:alpine as prod

WORKDIR /app

COPY ./default.conf /etc/nginx/conf.d/default.conf

COPY --from=builder /app/dist/ /var/www/html/
